version: '3'

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - "4000:3306"
    command: --innodb-use-native-aio=0
    volumes:
      - .docker/dbdata:/var/lib/mysql
      - .docker/mysql/transferencia-facil-db:/var/lib/mysql/transferencia@002dfacil
    environment:
      MYSQL_DATABASE: transferencia-facil
      MYSQL_ROOT_PASSWORD: 1234
    networks:
     - app-network

  app:
    build: .
    container_name: app
    ports:
      - "5000:80"
    volumes:
      - ./:/usr/share/nginx
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql
    networks:
     - app-network

networks:
  app-network:
    driver: bridge
